CREATE TABLE [dbo].[Exam](
	[ID]				INT		NOT NULL IDENTITY(1,1) CONSTRAINT [PK_EXAM_ID] PRIMARY KEY, 
	[SubjectID]		INT		NOT NULL CONSTRAINT [FK_EXAM_SUBJECTID] FOREIGN KEY REFERENCES [dbo].[Subject](ID),
	[StudentID]		INT		NOT NULL CONSTRAINT [FK_EXAM_STUDENTID] FOREIGN KEY REFERENCES [dbo].[Student](ID), 
	[Score]			INT		NOT NULL CONSTRAINT [CK_EXAM_SCORE] CHECK (Score BETWEEN 1 AND 5), 
	[Date]			DATETIME
)